type:
    non_small_cell_carcinoma: 25
    adenocarcinoma: 25
    bronchioloalveolar_adenocarcinoma: 25
    acinar_adenocarcinoma: 25
    adenosquamous_carcinoma: 25
    cancer: 2
    carcinoma: 2 
    large_cell_carcinoma: 25
    large_cell_neuroendocrine_carcinoma: 25
    large_cell_undifferentiated_carcinoma: 25
location:
    lung: 10
    bronchus: 10
    left: 5
    upper_lobe: 10
    left_bronchus: 10
    left_lower_lobe: 10
    left_upper_lobe: 10
    middle_lobe: 10
    right: 5
    right_bronchus: 10
    right_lower_lobe: 10
    right_middle_lobe: 10
    right_upper_lobe: 10
    trachea: 10
genes:
    ERBB4: 3
    PDGFRA: 3
    FLT1: 2
    KDR: 3
    RET: 2
    BRCA2: 4
    ROS1: 2
    MAP3K4: 4
    JAK3: 3
    ERBB3: 3
    MYC: 2
    NOTCH4: 2
    PIK3CD: 2
    CDK12: 2
    NOTCH1: 2
    PTEN: 2
    SMARCB1: 2
    PDGFRB: 2
    SMO: 2
    PIK3CB: 2
    MAP2K1: 2
    MAPK8: 2
    MAP2K2: 2
    CDKN1B: 2
    CDK3: 2
